/*
 * Convert between temperature and EMF (electromotive force) of
 * thermocouples based on ITS-90 Thermocouple Database:
 * https://srdata.nist.gov/its90/main/
 *
 * This is an auto-generated file.
 * (created by: nistcoeff.pl all.tab)
 *
 * !!! DO NOT EDIT THIS FILE. !!!
 *
*/

#ifndef __NIST_ITS90_H__
#define __NIST_ITS90_H__

#include "nist-its90-config.h"

#ifdef NIST_ITS90_USE_DOUBLE
typedef double FLOAT;
#else
typedef float FLOAT;
#endif

#ifdef __cplusplus
extern "C" {
#endif

FLOAT polynomial(FLOAT x, FLOAT *coeff, int size);

FLOAT temp2emf_B(FLOAT temperature);
FLOAT emf2temp_B(FLOAT emf);

FLOAT temp2emf_E(FLOAT temperature);
FLOAT emf2temp_E(FLOAT emf);

FLOAT temp2emf_J(FLOAT temperature);
FLOAT emf2temp_J(FLOAT emf);

FLOAT temp2emf_K(FLOAT temperature);
FLOAT emf2temp_K(FLOAT emf);

FLOAT temp2emf_N(FLOAT temperature);
FLOAT emf2temp_N(FLOAT emf);

FLOAT temp2emf_R(FLOAT temperature);
FLOAT emf2temp_R(FLOAT emf);

FLOAT temp2emf_S(FLOAT temperature);
FLOAT emf2temp_S(FLOAT emf);

FLOAT temp2emf_T(FLOAT temperature);
FLOAT emf2temp_T(FLOAT emf);

#ifdef __cplusplus
}
#endif

#endif /* __NIST_ITS90_H__ */
